name: Build and Test

on: [push]

jobs:
  linux_build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Apt Dependencies
        run: sudo apt-get install libboost-dev libblas-dev liblapack-dev

      - name: Configure CMake
        working-directory: ./
        shell: bash
        run: cmake -DCMAKE_BUILD_TYPE=Release .

      - name: Build
        working-directory: ./
        shell: bash
        run: cmake --build . -j 2
        
      - name: listFiles
        working-directory: ./
        shell: bash
        run: ls

      - name: Run Tests
        working-directory: ./
        run: ctest --verbose
